### ISSUE TITLE
Compile with PARI

### ISSUE THREAD

**Issue by isuruf** [conda-forge/cysignals-feedstock#1]
I'm trying to package PARI and others for sagemath. This requires cysignals be compiled with PARI.
This introduces a dependency on PARI though. What do you think?

**Comment by dfroger** [comment]
Thanks @isuruf for opening this issue, I was not aware that `cysignals` can be compiled with `PARI`. I think we should do it, and have `cysignals` package depends on `PARI`.

I see that [pari recipe](https://github.com/conda-forge/staged-recipes/pull/2370) has been merged, so feedstock shoud be ready soon.

So we will just have to add `PARI` as build and install requirements, and [configure](https://github.com/sagemath/cysignals/blob/86c7d65df029a1b95b55734278d30ba5d345bc73/configure.ac#L21-L28) will define `HAVE_PARI`?

**Comment by isuruf** [comment]
> So we will just have to add PARI as build and install requirements, and configure will define HAVE_PARI?

Yes, I've sent PR #2
